FROM eclipse-temurin:21-jre-alpine-3.24

WORKDIR /app

RUN apk upgrade --no-cache && addgroup -S appgroup && adduser -S -D -H -u 10001 -G appgroup appuser

COPY --chown=appuser:appgroup target/container-security-lab-1.0.0.jar app.jar

USER appuser

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
