FROM eclipse-temurin:21-jre

WORKDIR /app

RUN groupadd --system appgroup && useradd --system --gid appgroup --uid 10001 --no-create-home appuser

COPY --chown=appuser:appgroup target/container-security-lab-1.0.0.jar app.jar

USER appuser

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
