name: Hardened Container Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  secure-build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Verify Java
        run: java --version

      - name: Resolver las dependencias de Maven
        working-directory: hardened
        run: mvn dependency:resolve

      - name: Escaneos de seguridad de source y dependencias
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: ./hardened
          format: table
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: '0'

      - name: Run pruebas unitarias test
        working-directory: hardened
        run: mvn test

      - name: Construir aplicación hardenizada
        working-directory: hardened
        run: mvn clean package -DskipTests

      - name: Construir Imagen Docker Hardenizada
        run: |
          docker build -f hardened/Dockerfile.hardened -t container-security-lab:hardened hardened

      - name: Mostrar Imagen Docker
        run: docker images container-security-lab

      - name: Escanear imagen Hardenizada con Trivy
        uses: aquasecurity/trivy-action@master
        with: 
          image-ref: 'container-security-lab:hardened'
          format: 'table'
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: '0'
