name: Pipeline Inseguro

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-security-scan:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Verify Java
        run: java --version

      - name: Run unit tests
        working-directory: insecure
        run: mvn test

      - name: Build insecure application
        working-directory: insecure
        run: mvn clean package
