name: Pipeline Inseguro

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-security-scan:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Verify Java
        run: java --version

      - name: Run unit tests
        working-directory: insecure
        run: mvn test

      - name: Build insecure application
        working-directory: insecure
        run: mvn clean package
      
      - name: Build insecure Docker image
        run: |
          docker build \
            -f insecure/Dockerfile.insecure \
            -t container-security-lab:insecure \
            insecure

      - name: Show Docker image
        run: docker images container-security-lab

      - name: Scan insecure image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'container-security-lab:insecure'
          format: 'table'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true
          exit-code: '0'
